#----------------------------------
# Header
#

menu:
  Home: /
  Help: /help
  Thanks: /thanks
  API: /docs/api

rss: /atom.xml

#----------------------------------
# Footer
#

social:
  GitHub: https://github.com/ikesnowy/Algorithms-4th-Edition-in-Csharp
  Weibo: 
  Twitter: 
  LinkedIn: 
  Rss: /atom.xml

#----------------------------------
# Search
#

search_title: 搜索解答
search_subtitle: 目前已完成到 3.2
search_placeholder: 题目编号/关键字

#----------------------------------
# Comment
#

# fill in with your duoshuo/disqus short_name
duoshuo: 
disqus: 

#----------------------------------
# Analytics
#

# ga for google analytics
# ba for baidu analytics (百度统计)

ga: UA-121852990-1
ba: 1ba6aff1459206104682ef794c4d3eeb

#----------------------------------
# Miscellaneous
#

# author_page is your personal website url
author_page: 

home_title: 最近添加
archive_title: 归档
article_breadcrumb: 解答
page_breadcrumb: 页面

favicon: favicon.ico

#----------------------------------
